import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import classification_report
from sklearn.pipeline import Pipeline
from sklearn.calibration import CalibratedClassifierCV
import re
from collections import Counter

# Your existing data (x, y, priority) remains the same here...
x = [
    # Account Related (100)
    "How do I open a savings account with your bank?",
    "What documents are required for opening a joint account?",
    "I want to convert my regular savings account to a premium account",
    "What is the minimum balance requirement for a savings account?",
    "How can I update my mobile number linked to my bank account?",
    "I need to change my address in my bank records",
    "What is the process to add a nominee to my existing account?",
    "How do I close my savings account?",
    "Can I open a zero-balance account with your bank?",
    "What are the interest rates on savings accounts currently?",
    "Is there any charge for non-maintenance of minimum balance?",
    "How do I convert my single account to a joint account?",
    "I want to know about the senior citizen savings account benefits",
    "What documents are needed for KYC update?",
    "How do I merge two accounts I have in different branches?",
    "Can I open an account if I'm an NRI?",
    "What is the procedure to change my account from minor to major?",
    "How can I update my PAN card details in my account?",
    "What is a BSBDA account and am I eligible?",
    "I want to activate dormant account",
    "How to get a duplicate passbook for my account?",
    "What is the daily transaction limit for my savings account?",
    "Can I open a current account as an individual?",
    "How do I activate internet banking for my new account?",
    "Is there a limit on the number of transactions in a savings account?",
    "What are the charges for account statement?",
    "How can I update my Aadhaar in my bank account?",
    "Can I have multiple savings accounts in your bank?",
    "What is the process for name change in bank account after marriage?",
    "How do I reactivate my dormant account?",
    "What is the difference between savings and current account?",
    "I want to know the balance in my account",
    "How can I update my signature in my bank account?",
    "What are the benefits of premium savings account?",
    "Do you offer any special account for government employees?",
    "Can I convert my savings account to a salary account?",
    "What is the procedure to change my registered email ID?",
    "I need to know about the pensioner's savings account",
    "How can I check if my account is active?",
    "What is the process of freezing my bank account temporarily?",
    "How do I get my account number if I've lost my passbook?",
    "What is a sweep-in facility in savings account?",
    "Can I open a bank account for my minor child?",
    "How do I link multiple accounts under a single customer ID?",
    "What are the charges for not maintaining quarterly average balance?",
    "How can I know the IFSC code of my account's branch?",
    "I want to opt for email statements instead of physical ones",
    "What's the procedure to change from one account type to another?",
    "Can I open a special account for my small business?",
    "How do I get Form 16A for my fixed deposit interest?",
    "What is the process for biometric verification of my account?",
    "Can I operate my account from any branch?",
    "I need information about FCNR accounts",
    "How do I update my occupation details in my account?",
    "What are the benefits of a women's savings account?",
    "How do I request a statement of account for the last financial year?",
    "Can foreigners open bank accounts in India?",
    "What is the procedure to become a premium customer?",
    "How can I check transactions older than 6 months in my account?",
    "What is the difference between savings account and jan dhan account?",
    "How do I add a joint holder to my existing account?",
    "Can I operate my account with a thumbprint if I cannot sign?",
    "What is a basic savings bank deposit account?",
    "How do I update my income range in my account details?",
    "What is the procedure for changing my bank branch?",
    "Is there any annual maintenance charge for my savings account?",
    "How can I know the interest credited to my account in the last financial year?",
    "I want to update my profile picture in the bank records",
    "What are the eligibility criteria for a premium savings account?",
    "How do I delink my Aadhaar from bank account?",
    "Can I have a joint account with more than two holders?",
    "What is the process for enabling international transactions on my account?",
    "How do I get a certificate of balance for visa purposes?",
    "What are the charges for SMS alerts on my account?",
    "Can I have different nominees for different accounts?",
    "How do I get a letter from the bank confirming my account details?",
    "What happens to my account if I leave India permanently?",
    "How can I update my mother's maiden name in bank records?",
    "Can I open an account with just my Aadhaar card?",
    "What is the procedure for adding a power of attorney to operate my account?",
    "How do I enable auto-renewal for my FD account?",
    "Can I change my primary account linked to my debit card?",
    "What are the benefits of linking my Aadhaar to bank account?",
    "How do I verify if my account is properly KYC compliant?",
    "What is the interest calculation method for savings account?",
    "How do I get my Customer ID if I only know my account number?",
    "What are the special features of salary account?",
    "Can an illiterate person open a bank account?",
    "How do I update my income tax details in my account?",
    "What is the procedure for operating a minor's account?",
    "How can I link my GST number to my business account?",
    "What is the maximum number of joint holders allowed in a savings account?",
    "How do I get my 15G/15H form processed for my deposits?",
    "Can I open an account online without visiting the branch?",
    "What are the charges for account closure before one year?",
    
    # Loans and Mortgages (100)
    "What is the current home loan interest rate?",
    "How do I apply for education loan for studying abroad?",
    "What documents are required for personal loan application?",
    "Can I get a pre-approved loan as an existing customer?",
    "What is the maximum amount I can get for a car loan?",
    "How to check my loan eligibility online?",
    "What is the processing fee for home loans?",
    "Can I transfer my existing home loan from another bank?",
    "How long does it take to process a business loan application?",
    "What is the tenure available for education loans?",
    "Can I get a loan against fixed deposit?",
    "How do I check my loan account statement?",
    "What is the procedure to foreclose my personal loan?",
    "Are there any charges for prepayment of home loan?",
    "How can I get a top-up on my existing home loan?",
    "What is the EMI for a 30 lakh home loan for 20 years?",
    "Do you provide loans for agricultural purposes?",
    "What is the maximum age limit for loan repayment?",
    "How do I apply for mudra loan for my small business?",
    "Can I get moratorium period for education loan?",
    "What is the interest rate on gold loans currently?",
    "How do I reschedule my loan EMI?",
    "What security/collateral is required for a business loan?",
    "Can I pay my loan EMI using credit card?",
    "What is the procedure for loan against property?",
    "How to get a home loan subsidy under PMAY scheme?",
    "What is the maximum loan-to-value ratio for home loans?",
    "Can I get a personal loan with my current CIBIL score of 650?",
    "What are the charges for loan statement and NOC?",
    "How do I check my outstanding loan balance?",
    "Can I get a loan without income proof?",
    "What is the difference between flexi loan and term loan?",
    "How do I change the EMI date for my existing loan?",
    "What are the tax benefits available on home loan?",
    "Can I transfer my car loan to another person?",
    "What is the eligibility criteria for MSME loans?",
    "How do I get duplicate loan documents?",
    "Can NRIs apply for home loans in India?",
    "What is the processing time for personal loan disbursement?",
    "How to get a loan against mutual funds or shares?",
    "What is the minimum income required for education loan?",
    "How do I get my interest certificate for income tax purposes?",
    "What is the policy for joint applicants in home loans?",
    "Can I get a loan against my insurance policy?",
    "What happens if I miss an EMI payment?",
    "How do I calculate the total interest paid on my loan?",
    "What is the difference between secured and unsecured loans?",
    "Can I get a loan for home renovation?",
    "What documents are needed for loan against property?",
    "How do I apply for a loan under stand-up India scheme?",
    "What is the foreclosure charges for car loan?",
    "Can I change my loan tenure after disbursement?",
    "How do I get a balance transfer for my existing personal loan?",
    "What is the maximum limit for unsecured business loans?",
    "Can I apply for a wedding loan?",
    "What is the process for getting a loan statement for visa purposes?",
    "How long does my employment need to be to qualify for a personal loan?",
    "What are the interest rates for loans against rental property?",
    "Can I get a home loan for under-construction property?",
    "What is the status of my loan application?",
    "How do I link my loan account to net banking?",
    "What is the minimum CIBIL score required for loan approval?",
    "Can I get a loan against my provident fund?",
    "What is the part-payment procedure for home loans?",
    "How do I get an education loan for vocational courses?",
    "What is the maximum tenure for personal loans?",
    "Can I apply for multiple loans simultaneously?",
    "What is the process for foreclosure of loan against property?",
    "How do I get a loan against my shop/commercial property?",
    "What documents are required for loan restructuring?",
    "Can I get a loan against my salary?",
    "What is the interest rate for loan against securities?",
    "How do I update my details in my existing loan account?",
    "What is the eligibility for PM SVANidhi loan?",
    "Can I get instant personal loan disbursal?",
    "What is the difference between EMI and pre-EMI in home loans?",
    "How do I check if my loan has been approved?",
    "What are gold loan per gram rates today?",
    "Can I get education loan without collateral?",
    "What is the process to get NOC after loan closure?",
    "How do I dispute charges on my loan account?",
    "What is DSA in loan processing?",
    "Can I get a top-up on my existing personal loan?",
    "What is the maximum loan amount for self-employed individuals?",
    "How do I get duplicate NOC for my closed loan?",
    "What documents are required for foreclosure of home loan?",
    "Can I switch from floating to fixed interest rate on my loan?",
    "How do I get a loan statement by email?",
    "What is MCLR and how does it affect my loan EMI?",
    "Can I get car loan for electric vehicles?",
    "What is the processing time for loan against fixed deposit?",
    "How do I get my loan linked to Aadhaar?",
    "What is the procedure for getting a rural housing loan?",
    "Can I get a personal loan if I'm self-employed?",
    "What are the charges for loan account statement?",
    "How do I change the security for my existing loan?",
    "What is the eligibility for pensioners' loan scheme?",
    "Can I add a co-applicant to my existing loan?",
    
    # Credit and Debit Cards (100)
    "How do I apply for a credit card?",
    "What is the procedure to block my lost debit card?",
    "How can I increase the credit limit on my card?",
    "What is the annual fee for premium credit cards?",
    "How do I generate debit card PIN?",
    "Can I convert credit card purchase into EMI?",
    "What is the cash withdrawal limit on my debit card?",
    "How do I redeem reward points on my credit card?",
    "What documents are required for credit card application?",
    "How to change the billing cycle of my credit card?",
    "Can I get an add-on card for my family member?",
    "What is the charges for international transactions on debit card?",
    "How do I activate my new credit card?",
    "What is the minimum repayment amount for credit card bills?",
    "How do I update the mobile number linked to my debit card?",
    "What are the benefits of platinum debit card?",
    "Can I use my debit card internationally?",
    "How do I check my credit card statement online?",
    "What is the interest rate on credit card outstanding amount?",
    "How do I apply for replacement of damaged debit card?",
    "Can I get a credit card against fixed deposit?",
    "What is the daily transaction limit on my credit card?",
    "How do I link multiple accounts to one debit card?",
    "What is the joining fee for your bank's credit card?",
    "How to report unauthorized transactions on my card?",
    "Can I get a virtual debit card for online transactions?",
    "What is the validity period of my debit card?",
    "How do I change my credit card PIN?",
    "What are the offers currently available on credit cards?",
    "How do I enable international transactions on my debit card?",
    "Can I get credit card statement by email?",
    "What is the cash advance fee on credit cards?",
    "How do I request a duplicate card if my card is damaged?",
    "What is the eligibility criteria for premium credit cards?",
    "How do I set transaction alerts on my debit card?",
    "Can I get instant credit card approval?",
    "What is the procedure to surrender my credit card?",
    "How do I get my debit card delivered to a different address?",
    "What are the charges for late payment of credit card bill?",
    "How do I request a card statement for visa purposes?",
    "Can I get a secured credit card against my fixed deposit?",
    "What is the process to dispute a transaction on my credit card?",
    "How do I activate contactless payment feature on my debit card?",
    "What is the credit card payment due date?",
    "How do I link my credit card to UPI?",
    "Can I get a corporate credit card for my business?",
    "What is the annual percentage rate on my credit card?",
    "How do I get emergency card replacement when abroad?",
    "What are the benefits of co-branded credit cards?",
    "How do I change the name on my debit card?",
    "Can I increase the withdrawal limit on my debit card temporarily?",
    "What is the validity of reward points on my credit card?",
    "How do I get my credit score before applying for a card?",
    "What is the procedure to close my credit card account?",
    "How do I activate international usage on my credit card?",
    "Can I get a credit card with no annual fee?",
    "What are the charges for cash withdrawal from credit card?",
    "How do I get a replacement for expired debit card?",
    "What benefits do I get with airport lounge access on my card?",
    "How do I opt out of auto-renewal for my credit card?",
    "Can I get a debit card for my minor child's account?",
    "What is the fuel surcharge waiver limit on credit cards?",
    "How do I convert credit card dues to EMI after purchase?",
    "What is the turnaround time for credit card delivery?",
    "How do I enable DND service for credit card offers?",
    "Can I get instant virtual credit card?",
    "What are the charges for card replacement?",
    "How do I request a credit limit increase?",
    "What is the daily purchase limit on my debit card?",
    "How do I register for 3D secure password for online transactions?",
    "Can I have multiple credit cards from your bank?",
    "What is the process for upgrading my debit card?",
    "How do I check available credit limit on my card?",
    "What is the minimum income requirement for credit card?",
    "How do I activate my card for contactless transactions?",
    "Can I get a supplementary card for my spouse?",
    "What is the process for disputing a debit card transaction?",
    "How do I check the status of my credit card application?",
    "What are the benefits of metal credit cards?",
    "How do I request a credit card statement for the last financial year?",
    "Can I get a debit card if I have a joint account?",
    "What is the procedure for hot-listing my card?",
    "How do I activate SMS alerts for card transactions?",
    "What is the grace period for credit card bill payment?",
    "How do I enable international roaming on my card?",
    "Can I get credit card against mutual funds?",
    "What are the insurance benefits with my premium credit card?",
    "How do I get my card linked to Fastag?",
    "What is the difference between charge card and credit card?",
    "How do I activate my card for e-commerce transactions?",
    "Can I request an EMI conversion through mobile banking?",
    "What is the minimum amount eligible for EMI conversion?",
    "How do I check when my debit card will expire?",
    "What are the milestone benefits on credit card spending?",
    "How do I get GST invoice for credit card annual fees?",
    "Can I request a credit card without income proof?",
    "What is the difference between signature and PIN transactions?",
    "How do I request a credit card with lower interest rate?",
    "What are the charges for declined transactions?",
    
    # Digital Banking (100)
    "How do I register for internet banking?",
    "What is the procedure to reset net banking password?",
    "How can I update mobile number in mobile banking app?",
    "What is the daily transaction limit in BHIM UPI?",
    "How do I link my accounts to mobile banking?",
    "Can I use net banking for international funds transfer?",
    "What are the charges for NEFT transactions online?",
    "How do I generate MMID for mobile banking?",
    "What is the process for registering beneficiary in net banking?",
    "How do I activate UPI on my bank account?",
    "Can I schedule recurring payments through internet banking?",
    "What are the steps to download bank statement online?",
    "How do I register for e-statement service?",
    "What is the procedure to apply for cheque book online?",
    "How can I update my PAN details through net banking?",
    "What is the transaction limit for IMPS transfers?",
    "How do I link multiple accounts under one customer ID in online banking?",
    "Can I apply for fixed deposit through mobile banking?",
    "What are the steps to generate account statement for tax filing online?",
    "How do I register complaints through internet banking?",
    "What is the procedure to enable biometric login for mobile banking?",
    "How can I setup bill payment reminders in digital banking?",
    "What are the charges for mobile banking services?",
    "How do I reset MPIN for mobile banking?",
    "Can I update my address through net banking?",
    "What is the process for cardless cash withdrawal using mobile app?",
    "How do I enable international transactions in internet banking?",
    "What are the steps to link Aadhaar through online banking?",
    "How can I check my loan details in mobile banking?",
    "What is the procedure to stop cheque payment online?",
    "How do I register for WhatsApp banking service?",
    "Can I apply for locker facility through internet banking?",
    "What are the steps to create virtual debit card online?",
    "How do I update nomination details through net banking?",
    "What is the process for FATCA declaration online?",
    "How can I track my debit card delivery through mobile app?",
    "What are the service charges visible in internet banking?",
    "How do I enable SMS alerts through online banking?",
    "Can I update my email ID through mobile banking?",
    "What is the procedure to register for NACH mandate online?",
    "How do I apply for new credit card through net banking?",
    "What are the steps to link my PAN with account online?",
    "How can I generate TDS certificate through internet banking?",
    "What is the process for setting up standing instructions online?",
    "How do I enable face recognition login for mobile banking?",
    "Can I request account statement by email through net banking?",
    "What are the steps to update my profile picture in mobile app?",
    "How do I enable QR code payments in mobile banking?",
    "What is the procedure to activate dormant account online?",
    "How can I check my CIBIL score through net banking?",
    "What are the steps to enable dark mode in mobile banking app?",
    "How do I link my demat account to internet banking?",
    "Can I update my occupation details through online banking?",
    "What is the process for registering mobile number for UPI?",
    "How do I generate OTP for high-value transactions?",
    "What are the steps to setup direct debit facility online?",
    "How can I check my reward points through mobile banking?",
    "What is the procedure to update KYC details online?",
    "How do I set transaction limits in mobile banking?",
    "Can I download Form 16A through internet banking?",
    "What are the steps to register for digital passbook?",
    "How do I enable notifications for all transactions?",
    "What is the process for foreign currency transfer through net banking?",
    "How can I check status of my cheque through mobile app?",
    "What are the steps to register multiple mobile numbers for alerts?",
    "How do I deregister my mobile number from UPI?",
    "Can I apply for loan through internet banking?",
    "What is the procedure to link Google Pay with my bank account?",
    "How do I manage beneficiaries in mobile banking?",
    "What are the steps to enable fingerprint login?",
    "How can I check my spending analysis in digital banking?",
    "What is the process for reporting unauthorized transaction online?",
    "How do I update my income range through net banking?",
    "Can I open fixed deposit for someone else through mobile banking?",
    "What are the steps to set favorite transactions in internet banking?",
    "How do I enable or disable international transactions online?",
    "What is the procedure to raise dispute for failed transactions?",
    "How can I change UPI PIN through mobile banking?",
    "What are the steps to link multiple bank accounts to single UPI ID?",
    "How do I enable location-based security in mobile app?",
    "Can I apply for insurance products through internet banking?",
    "What is the process for scheduling NEFT transactions?",
    "How do I enable voice banking services?",
    "What are the steps to register for tax saver fixed deposit online?",
    "How can I update my signature through net banking?",
    "What is the procedure to enable two-factor authentication?",
    "How do I link FastTag to my bank account through mobile app?",
    "Can I change my username for net banking?",
    "What are the steps to register for doorstep banking services online?",
    "How do I enable card control features in mobile banking?",
    "What is the process for downloading interest certificate online?",
    "How can I check my GST payments history through internet banking?",
    "What are the steps to link PhonePe with my bank account?",
    "How do I update my communication preferences online?",
    "Can I apply for virtual credit card through mobile banking?",
    "What is the procedure to schedule bulk payments in internet banking?",
    "How do I enable payment notifications for specific accounts?",
    
    # Investments and Wealth Management (100)
    "What are the current fixed deposit interest rates?",
    "How do I open a PPF account with your bank?",
    "What is the procedure to redeem mutual funds?",
    "How can I open a demat account?",
    "What are the tax benefits for senior citizen savings scheme?",
    "How do I invest in government bonds through the bank?",
    "What is the lock-in period for tax-saving fixed deposits?",
    "How can I transfer shares from one demat account to another?",
    "What are the charges for demat account maintenance?",
    "How do I start an SIP in mutual funds?",
    "What is the minimum investment amount for recurring deposit?",
    "How can I check my PPF account balance online?",
    "What are the wealth management services offered by your bank?",
    "How do I prematurely withdraw my fixed deposit?",
    "What is the difference between cumulative and non-cumulative FD?",
    "How can I invest in IPOs through my bank account?",
    "What are the current interest rates for recurring deposits?",
    "How do I transfer my existing mutual fund portfolio to your bank?",
    "What is the procedure to open NPS account?",
    "How can I calculate returns on my fixed deposit?",
    "What are the different types of mutual funds available?",
    "How do I nominate someone for my investments?",
    "What is the minimum balance required for wealth management services?",
    "How can I update nominee details for my demat account?",
    "What are the tax implications on premature FD withdrawal?",
    "How do I invest in sovereign gold bonds?",
    "What is the procedure to close my recurring deposit?",
    "How can I link my PAN to my investment account?",
    "What are the benefits of sweep-in fixed deposits?",
    "How do I track performance of my mutual fund investments?",
    "What is the minimum investment in tax-saving FDs?",
    "How can I open a corporate FD account?",
    "What are the exit load charges for mutual funds?",
    "How do I renew my fixed deposit online?",
    "What is the difference between direct and regular mutual funds?",
    "How can I convert physical shares to demat form?",
    "What are the current FCNR deposit rates?",
    "How do I update my risk profile for investments?",
    "What is the procedure to pledge shares in my demat account?",
    "How can I invest in digital gold through your bank?",
    "What are the charges for mutual fund investments?",
    "How do I generate capital gains statement for my investments?",
    "What is the difference between PPF and sukanya samriddhi account?",
    "How can I open a joint demat account?",
    "What are the current interest rates for senior citizen deposits?",
    "How do I apply for Sukanya Samriddhi Account?",
    "What is the procedure to transfer PPF account to your bank?",
    "How can I invest in ELSS for tax saving?",
    "What are the benefits of RD over FD?",
    "How do I generate TDS certificate for my fixed deposits?",
    "What is the process for investing in corporate bonds?",
    "How can I check the status of my IPO application?",
    "What are the interest rates for NRE fixed deposits?",
    "How do I calculate the maturity amount of recurring deposit?",
    "What is the procedure to convert RD to FD?",
    "How can I invest in liquid funds through your bank?",
    "What are the types of demat accounts available?",
    "How do I link my demat account with trading account?",
    "What is the penalty for premature closure of recurring deposit?",
    "How can I avail loan against my mutual funds?",
    "What are the different investment options for retirement planning?",
    "How do I set up SWP (Systematic Withdrawal Plan) in mutual funds?",
    "What is the procedure to invest in IDFs (Infrastructure Debt Funds)?",
    "How can I transfer my existing PPF from post office to bank?",
    "What are the tax benefits of NPS investment?",
    "How do I invest in index funds?",
    "What is the procedure to open a Senior Citizen Savings Scheme account?",
    "How can I invest in overnight funds?",
    "What are the benefits of goal-based investing?",
    "How do I redeem my sovereign gold bonds before maturity?",
    "What is the difference between debt and equity mutual funds?",
    "How can I start a STP (Systematic Transfer Plan)?",
    "What are the current rates for tax-saving fixed deposits?",
    "How do I check unclaimed investments in my name?",
    "What is the procedure to invest in REITs through your bank?",
    "How can I get detailed portfolio analysis of my investments?",
    "What are the advantages of corporate deposits over bank deposits?",
    "How do I update my nomination for all my investments at once?",
    "What is the procedure to invest in capital gain bonds?",
    "How can I invest in foreign equity through your bank?",
    "What are the alternatives to fixed deposits with better returns?",
    "How do I calculate LTCG on my mutual fund investments?",
    "What is the procedure to start a trigger-based SIP?",
    "How can I track all my investments in one place?",
    "What are the different types of government securities available for retail investors?",
    "How do I generate income tax statements for all my investments?",
    "What is the procedure to invest in municipal bonds?",
    "How can I invest in commodity ETFs?",
    "What are the benefits of multi-asset allocation funds?",
    "How do I set up a monthly income plan through investments?",
    "What is the procedure to change my investment advisor?",
    "How can I invest in arbitrage funds?",
    "What are the tax implications of dividends from investments?",
    "How do I transfer investment portfolio after death of account holder?",
    "What is the procedure to invest in target maturity funds?",
    "How can I get advice on portfolio rebalancing?",
    "What are the current rates for floating rate savings bonds?",
    "How do I close my demat account?"
     "How do I link my Aadhaar card to my bank account?",
    "What is the last date to link Aadhaar with bank account?",
    "Is it mandatory to link Aadhaar with my savings account?",
    "Can I update my Aadhaar details through net banking?",
    "What happens if I don't link my Aadhaar to bank account?",
    "How to check if my Aadhaar is already linked to bank account?",
    "Can I open a bank account only with Aadhaar card?",
    "What documents are needed along with Aadhaar for opening an account?",
    "How do I de-link my Aadhaar from bank account?",
    "I've changed my mobile number in Aadhaar, how to update it in bank records?",
    "Is e-Aadhaar accepted for KYC verification in banks?",
    "Can I withdraw money using Aadhaar-enabled payment system?",
    "How to do Aadhaar-based verification for internet banking?",
    "What is Aadhaar seeding in banking terms?",
    "How secure is Aadhaar authentication for banking transactions?",
    "Can I update my address in bank records through Aadhaar?",
    "Is biometric authentication mandatory for Aadhaar-linked accounts?",
    "What is the procedure for Aadhaar-based account opening?",
    "How to enable Aadhaar-based OTP for online transactions?",
    "Can NRIs link Aadhaar to their NRE/NRO accounts?",
    "What is the difference between PAN and Aadhaar linking to bank account?",
    "How to get mini statement using Aadhaar at micro ATMs?",
    "Is Aadhaar mandatory for senior citizen accounts?",
    "Can I link multiple bank accounts to one Aadhaar number?",
    "How to authorize Aadhaar-enabled payment through banking app?",
    "What is AEPS (Aadhaar Enabled Payment System)?",
    "How to register for AEPS banking service?",
    "Can I receive direct subsidy benefits without Aadhaar-linked account?",
    "What is the procedure to change Aadhaar linked to my bank account?",
    "How to generate Aadhaar-based UPI ID?",
    "Is masked Aadhaar acceptable for banking purposes?",
    "What is Aadhaar Pay and how does it work with my bank account?",
    "Can I link virtual Aadhaar to my bank account?",
    "How to use Aadhaar for cardless cash withdrawal?",
    "What are the benefits of linking Aadhaar to bank account?",
    "How to check if unauthorized Aadhaar linking has happened to my account?",
    "What is e-KYC using Aadhaar and how to complete it?",
    "Can I use Aadhaar instead of debit card at ATMs?",
    "Is there a charge for Aadhaar authentication at bank branches?",
    "How to verify if my Aadhaar has been correctly linked to account?",
    "What are the alternatives if I don't want to link Aadhaar?",
    "Can I use Aadhaar for internet banking password reset?",
    "How to enable fingerprint authentication for Aadhaar banking?",
    "What is offline Aadhaar verification for bank accounts?",
    "Can I use Aadhaar for inter-bank fund transfers?",
    "How secure is my bank account when linked with Aadhaar?",
    "Can I open a joint account using Aadhaar?",
    "What details from my Aadhaar are shared with the bank?",
    "How to link Aadhaar to corporate account?",
    "Is Aadhaar mandatory for cash transactions above 50,000 rupees?",
    "Can minors link their Aadhaar to bank accounts?",
    "How to update Aadhaar demographic details through banking services?",
    "What is the Aadhaar mapper in banking apps?",
    "Can I get loan without Aadhaar in India?",
    "How to check which banks have access to my Aadhaar details?",
    "Is Aadhaar required for mobile banking registration?",
    "What is the difference between physical and e-Aadhaar for banking?",
    "Can I check my account balance using Aadhaar at micro ATMs?",
    "How to change biometric authentication to OTP for Aadhaar banking?",
    "What are Aadhaar Enabled Branch Services?",
    "Can I use Aadhaar for international banking services?",
    "How to activate dormant account using Aadhaar?",
    "What are the RBI guidelines on Aadhaar usage in banking?",
    "Can I update my income tax details using Aadhaar in bank?",
    "How to register for Aadhaar-based subsidy schemes through bank?",
    "What is the process of Aadhaar authentication failure resolution?",
    "Can I use Aadhaar to update nominee details in my account?",
    "How to enable iris authentication for Aadhaar banking?",
    "What is the difference between Aadhaar mapping and Aadhaar linking?",
    "Can I get duplicate passbook using only Aadhaar verification?",
    "How to receive LPG subsidy in Aadhaar-linked account?",
    "What is Aadhaar vault in banking security?",
    "Can I use Aadhaar for standing instructions setup?",
    "How to enable face authentication for Aadhaar banking?",
    "What is the UID token used instead of Aadhaar number in banks?",
    "Can I use Digilocker Aadhaar for bank account opening?",
    "How to report unauthorized use of my Aadhaar in banking?",
    "What is the Aadhaar authentication log maintained by banks?",
    "Can I use Aadhaar to transfer my account to another branch?",
    "How to use Aadhaar for digital signature in banking transactions?",
    "What are the privacy concerns with Aadhaar linking to bank accounts?",
    "Can I use Aadhaar for pension account verification?",
    "How to use Aadhaar for automatic KYC renewal?",
    "What is the difference between demographic and biometric Aadhaar authentication in banking?",
    "Can I use Aadhaar for paperless account opening?",
    "How to check if my Aadhaar is being used for DBT schemes?",
    "What is XML signing in Aadhaar-based banking?",
    "Can I use Aadhaar for foreign remittance KYC?",
    "How to generate Aadhaar virtual ID for banking purposes?",
    "What is the validity of Aadhaar OTP for banking transactions?",
    "Can I update my gender information in bank through Aadhaar?",
    "How to opt-out of Aadhaar authentication in banking?",
    "What is NPCI mapper for Aadhaar-based payments?",
    "Can I use Aadhaar for banking services without a smartphone?",
    "How to retrieve forgotten customer ID using Aadhaar?",
    "What is QR code-based Aadhaar verification in banking?",
    "Can I use Aadhaar to merge multiple customer IDs?",
    "How to resolve Aadhaar name mismatch issues with bank records?"
]

y= [
    # Account Related (100 entries)
    "account related", "account related", "account related", "account related", "account related",
    "account related", "account related", "account related", "account related", "account related",
    "account related", "account related", "account related", "account related", "account related",
    "account related", "account related", "account related", "account related", "account related",
    "account related", "account related", "account related", "account related", "account related",
    "account related", "account related", "account related", "account related", "account related",
    "account related", "account related", "account related", "account related", "account related",
    "account related", "account related", "account related", "account related", "account related",
    "account related", "account related", "account related", "account related", "account related",
    "account related", "account related", "account related", "account related", "account related",
    "account related", "account related", "account related", "account related", "account related",
    "account related", "account related", "account related", "account related", "account related",
    "account related", "account related", "account related", "account related", "account related",
    "account related", "account related", "account related", "account related", "account related",
    "account related", "account related", "account related", "account related", "account related",
    "account related", "account related", "account related", "account related", "account related",
    "account related", "account related", "account related", "account related", "account related",
    "account related", "account related", "account related", "account related", "account related",
    "account related", "account related", "account related", "account related", "account related",
    "account related", "account related", "account related", "account related", "account related",
    
    # Loans and Mortgages (100 entries)
    "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages",
    "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages",
    "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages",
    "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages",
    "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages",
    "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages",
    "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages",
    "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages",
    "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages",
    "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages",
    "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages",
    "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages",
    "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages",
    "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages",
    "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages",
    "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages",
    "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages",
    "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages",
    "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages",
    "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages", "loans and mortgages",
    
    # Credit and Debit Cards (100 entries)
    "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards",
    "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards",
    "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards",
    "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards",
    "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards",
    "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards",
    "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards",
    "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards",
    "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards",
    "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards",
    "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards",
    "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards",
    "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards",
    "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards",
    "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards",
    "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards",
    "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards",
    "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards",
    "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards",
    "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards", "credit and debit cards",
    
    # Digital Banking (100 entries)
    "digital banking", "digital banking", "digital banking", "digital banking", "digital banking",
    "digital banking", "digital banking", "digital banking", "digital banking", "digital banking",
    "digital banking", "digital banking", "digital banking", "digital banking", "digital banking",
    "digital banking", "digital banking", "digital banking", "digital banking", "digital banking",
    "digital banking", "digital banking", "digital banking", "digital banking", "digital banking",
    "digital banking", "digital banking", "digital banking", "digital banking", "digital banking",
    "digital banking", "digital banking", "digital banking", "digital banking", "digital banking",
    "digital banking", "digital banking", "digital banking", "digital banking", "digital banking",
    "digital banking", "digital banking", "digital banking", "digital banking", "digital banking",
    "digital banking", "digital banking", "digital banking", "digital banking", "digital banking",
    "digital banking", "digital banking", "digital banking", "digital banking", "digital banking",
    "digital banking", "digital banking", "digital banking", "digital banking", "digital banking",
    "digital banking", "digital banking", "digital banking", "digital banking", "digital banking",
    "digital banking", "digital banking", "digital banking", "digital banking", "digital banking",
    "digital banking", "digital banking", "digital banking", "digital banking", "digital banking",
    "digital banking", "digital banking", "digital banking", "digital banking", "digital banking",
    "digital banking", "digital banking", "digital banking", "digital banking", "digital banking",
    "digital banking", "digital banking", "digital banking", "digital banking", "digital banking",
    "digital banking", "digital banking", "digital banking", "digital banking", "digital banking",
    "digital banking", "digital banking", "digital banking", "digital banking", "digital banking",
    
    # Investments and Wealth Management (100 entries)
    "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management",
    "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management",
    "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management",
    "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management",
    "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management",
    "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management",
    "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management",
    "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management",
    "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management",
    "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management",
    "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management",
    "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management",
    "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management",
    "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management",
    "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management",
    "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management",
    "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management", "investments and wealth management",
    "investments and wealth management", "investments and wealth management",
    "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related",
    "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related",
    "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related",
    "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related",
    "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related",
    "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related",
    "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related",
    "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related",
    "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related",
    "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related",
    "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related",
    "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related",
    "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related",
    "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related",
    "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related",
    "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related",
    "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related",
    "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related",
    "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related", "aadhaar related",
    "aadhaar related", "aadhaar related"
]

priority = (
    ["high"] * 195 +
    ["medium"] * 195 +
    ["low"] * 194
)


# Generate some non-banking queries to train the validity classifier
non_banking_queries = [
    # Technology & Gadgets (50)
    "How to reset my iPhone to factory settings?",
    "What's the best laptop under $1000?",
    "Why is my WiFi connection so slow?",
    "How to clear cache on Android?",
    "Best photo editing app for beginners",
    "How to transfer photos from iPhone to PC?",
    "Why does my laptop overheat?",
    "How to block spam calls on Android?",
    "Best free antivirus software",
    "How to recover deleted files from USB?",
    "Why is my printer not connecting?",
    "How to speed up my old computer?",
    "Best wireless earbuds for running",
    "How to change my Instagram password?",
    "Why is my phone battery draining so fast?",
    "How to take a screenshot on Windows?",
    "Best budget smartphone camera",
    "How to delete my Facebook account?",
    "Why is my Bluetooth not pairing?",
    "How to update my graphics driver?",
    "Best password manager for 2023",
    "How to fix a cracked phone screen?",
    "Why is my Google Drive full?",
    "How to record my screen on Mac?",
    "Best external hard drive for backups",
    "How to change Netflix subscription plan?",
    "Why is my email not syncing?",
    "How to create a GIF from videos?",
    "Best smartwatch for fitness tracking",
    "How to enable dark mode on all apps?",
    "Why is my Zoom audio not working?",
    "How to clean my laptop keyboard?",
    "Best noise-cancelling headphones",
    "How to reset my router password?",
    "Why is my smart TV buffering?",
    "How to transfer contacts to new phone?",
    "Best free video editing software",
    "How to stop YouTube autoplay?",
    "Why is my microphone not working?",
    "How to check my data usage on iPhone?",
    "Best wireless charger for iPhone",
    "How to change my Twitter handle?",
    "Why is my laptop fan so loud?",
    "How to connect AirPods to Windows?",
    "Best budget tablet for students",
    "How to delete browsing history?",
    "Why is my app crashing?",
    "How to reduce photo file size?",
    "Best gaming mouse under $50",
    "How to turn off autocorrect?",

    # Food & Cooking (50)
    "How to make fluffy pancakes?",
    "Best substitute for eggs in baking",
    "Why does my bread dough not rise?",
    "How to cook perfect rice?",
    "Best way to store fresh herbs",
    "How to soften hard brown sugar?",
    "Why is my cake sinking in the middle?",
    "How to cut an onion without crying?",
    "Best vegetarian protein sources",
    "How to make homemade pizza dough?",
    "Why does my cheese sauce separate?",
    "How to tell if chicken is cooked?",
    "Best buttermilk substitute",
    "How to peel garlic quickly?",
    "Why is my whipped cream not stiff?",
    "How to make cold brew coffee?",
    "Best way to reheat fried chicken",
    "How to fix salty soup?",
    "Why does my pasta stick together?",
    "How to ripen avocados quickly?",
    "Best gluten-free flour blend",
    "How to make scrambled eggs creamy?",
    "Why is my pie crust tough?",
    "How to clean burnt pans?",
    "Best way to store bananas",
    "How to thicken runny jam?",
    "Why does my milk curdle when heating?",
    "How to make perfect hard-boiled eggs?",
    "Best sugar substitute for baking",
    "How to prevent apples from browning?",
    "Why is my homemade bread so dense?",
    "How to make creamy mashed potatoes?",
    "Best way to cook frozen vegetables",
    "How to fix broken mayonnaise?",
    "Why does my chocolate seize?",
    "How to make restaurant-style fried rice?",
    "Best way to store cut onions",
    "How to reduce spice in curry?",
    "Why is my frosting runny?",
    "How to make crispy roasted potatoes?",
    "Best way to clean a blender",
    "How to tell if fish is fresh?",
    "Why does my caramel crystallize?",
    "How to make fluffy omelette?",
    "Best way to store coffee beans",
    "How to peel boiled eggs easily?",
    "Why is my honey crystallized?",
    "How to make perfect grilled cheese?",
    "Best way to defrost meat quickly",

    # Health & Fitness (50)
    "How to relieve lower back pain?",
    "Best exercises for belly fat",
    "Why do I feel tired all the time?",
    "How to improve posture?",
    "Best vitamins for hair growth",
    "How to stop nighttime leg cramps?",
    "Why do I wake up with headaches?",
    "How to increase running stamina?",
    "Best yoga poses for beginners",
    "How to get rid of brain fog?",
    "Why does my knee hurt when bending?",
    "How to build muscle at home?",
    "Best foods for gut health",
    "How to stop sugar cravings?",
    "Why am I always hungry?",
    "How to improve sleep quality?",
    "Best stretches for office workers",
    "How to reduce bloating quickly?",
    "Why do I get dizzy when standing up?",
    "How to start intermittent fasting?",
    "Best home remedies for sore throat",
    "How to prevent shin splints?",
    "Why do my hands go numb at night?",
    "How to strengthen weak ankles?",
    "Best exercises for posture correction",
    "How to get rid of dark circles?",
    "Why does my shoulder click?",
    "How to do a proper push-up?",
    "Best natural sleep aids",
    "How to relieve sinus pressure?",
    "Why do I sweat so much?",
    "How to improve digestion naturally?",
    "Best way to track macros",
    "How to fix rounded shoulders?",
    "Why do my joints crack?",
    "How to do a proper squat?",
    "Best supplements for joint pain",
    "How to stop teeth grinding at night?",
    "Why do I get muscle cramps?",
    "How to increase flexibility?",
    "Best breathing exercises for anxiety",
    "How to relieve stiff neck?",
    "Why do my feet hurt in the morning?",
    "How to do a proper plank?",
    "Best foods for glowing skin",
    "How to stop overeating?",
    "Why do I get heartburn at night?",
    "How to strengthen core muscles?",
    "Best way to measure body fat",
    "How to relieve tension headaches?",

    # Travel (50)
    "Best time to visit Bali",
    "How to get over jet lag quickly?",
    "Why is my flight delayed?",
    "Best carry-on luggage for international travel",
    "How to find cheap hotel deals?",
    "What to pack for a week in Europe?",
    "Best travel credit card for miles",
    "How to avoid tourist scams in Paris?",
    "Why do my ears pop on planes?",
    "Best apps for finding local food",
    "How to get from airport to city center?",
    "What documents do I need for Mexico?",
    "Best way to exchange currency abroad",
    "How to prevent motion sickness?",
    "Why is my suitcase overweight?",
    "Best travel insurance for seniors",
    "How to say hello in 10 languages",
    "What's the tipping etiquette in Japan?",
    "Best portable charger for travel",
    "How to survive a long flight?",
    "Why do I need a visa for some countries?",
    "Best shoes for walking tours",
    "How to avoid getting sick while traveling?",
    "What's the best travel adapter?",
    "Best way to store documents while traveling",
    "How to find authentic local experiences?",
    "Why is my passport photo rejected?",
    "Best travel apps for offline use",
    "How to get around without knowing the language?",
    "What's the dress code in Dubai?",
    "Best time to book flights for summer",
    "How to take great travel photos?",
    "Why do I need travel insurance?",
    "Best way to pack shoes in luggage",
    "How to deal with travel anxiety?",
    "What's the best travel pillow?",
    "Best destinations for solo female travelers",
    "How to avoid pickpockets in crowded places?",
    "Why is my checked luggage lost?",
    "Best way to learn basic phrases",
    "How to stay connected abroad?",
    "What's the best travel backpack?",
    "Best way to track expenses while traveling",
    "How to get a refund for cancelled flight?",
    "Why do I feel tired after traveling?",
    "Best travel-sized toiletries",
    "How to find vegetarian food abroad?",
    "What's the best travel guidebook?",
    "Best way to prevent deep vein thrombosis",
    "How to get an international driver's permit?",

    # Entertainment (50)
    "How to watch Netflix offline?",
    "Best true crime documentaries on Netflix",
    "Why is my Spotify not working?",
    "How to get free books online?",
    "Best podcast apps for Android",
    "How to delete my YouTube history?",
    "Why does my TV keep buffering?",
    "Best family movies on Disney+",
    "How to cancel my Amazon Prime?",
    "Best way to organize digital photos",
    "Why is my Roku not connecting?",
    "How to watch Premier League in USA?",
    "Best apps for learning guitar",
    "How to fix scratched DVDs?",
    "Why is my Kindle not charging?",
    "Best board games for adults",
    "How to stream music for free?",
    "Best websites for free movies",
    "Why is my video quality poor?",
    "How to create a playlist on Spotify?",
    "Best VR games for beginners",
    "How to watch HBO Max abroad?",
    "Why does my game keep crashing?",
    "Best apps for tracking TV shows",
    "How to improve streaming quality?",
    "Best websites for audiobooks",
    "Why is my controller not connecting?",
    "How to download YouTube videos?",
    "Best free photo editing software",
    "Why is my movie download so slow?",
    "How to watch local channels without cable?",
    "Best apps for learning piano",
    "Why is my Fire Stick remote not working?",
    "How to organize my movie collection?",
    "Best websites for free sheet music",
    "Why is my audio out of sync?",
    "How to cast to my smart TV?",
    "Best apps for movie recommendations",
    "Why is my game lagging?",
    "How to watch NFL games online?",
    "Best websites for free ebooks",
    "Why is my Bluetooth speaker cutting out?",
    "How to fix pixelated video?",
    "Best apps for learning languages",
    "Why is my Netflix quality poor?",
    "How to watch NBA games without cable?",
    "Best websites for free courses",
    "Why is my game controller drifting?",
    "How to create a home theater system?",
    "Best apps for tracking books",

    # Home & Garden (50)
    "How to unclog a drain naturally?",
    "Best plants for low light conditions",
    "Why is my refrigerator not cooling?",
    "How to remove stains from carpet?",
    "Best way to organize a small closet",
    "How to fix a running toilet?",
    "Why are my houseplants dying?",
    "Best paint colors for small rooms",
    "How to clean mold from shower?",
    "Best way to store winter clothes",
    "Why is my AC not blowing cold air?",
    "How to get rid of fruit flies?",
    "Best herbs to grow indoors",
    "How to patch drywall holes?",
    "Why does my washing machine smell?",
    "Best way to clean windows streak-free",
    "How to remove wallpaper easily?",
    "Best furniture arrangement tips",
    "Why is my garbage disposal jammed?",
    "How to make small rooms look bigger?",
    "Best way to clean hardwood floors",
    "How to stop drafty windows?",
    "Why is my smoke detector beeping?",
    "Best way to organize kitchen cabinets",
    "How to remove rust from tools?",
    "Best plants for balcony gardens",
    "Why is my water pressure low?",
    "How to fix squeaky floors?",
    "Best way to store holiday decorations",
    "How to remove pet hair from furniture?",
    "Best way to clean stainless steel",
    "Why is my door sticking?",
    "How to get rid of ants naturally?",
    "Best way to arrange living room furniture",
    "How to fix a leaky faucet?",
    "Best indoor trees for low light",
    "Why is my oven not heating properly?",
    "How to remove candle wax from surfaces?",
    "Best way to organize a garage",
    "How to clean a mattress?",
    "Best way to store blankets",
    "Why is my dishwasher not draining?",
    "How to remove scratches from wood?",
    "Best plants for air purification",
    "How to fix a stuck window?",
    "Best way to clean leather furniture",
    "Why is my ceiling fan wobbling?",
    "How to remove grease from kitchen walls?",
    "Best way to organize a pantry",
    "How to get rid of musty smells?",
    "Best way to clean outdoor furniture",

    # Education & Learning (50)
    "How to improve my vocabulary?",
    "Best apps for learning Spanish",
    "Why do I forget what I study?",
    "How to take better notes?",
    "Best websites for free courses",
    "How to concentrate while studying?",
    "Why is math so hard for me?",
    "Best way to learn coding for beginners",
    "How to write a research paper?",
    "Best books to improve writing skills",
    "Why do I procrastinate so much?",
    "How to speed read effectively?",
    "Best YouTube channels for learning",
    "How to memorize things quickly?",
    "Why is my essay so boring?",
    "Best way to learn a language fast",
    "How to cite sources properly?",
    "Best apps for students",
    "Why do I get test anxiety?",
    "How to write a good thesis statement?",
    "Best websites for math help",
    "How to study for long hours?",
    "Why can't I understand physics?",
    "Best way to take online notes",
    "How to improve my grammar?",
    "Best free typing tutor software",
    "Why do I mix up similar words?",
    "How to write a book report?",
    "Best apps for organizing study notes",
    "How to understand complex concepts?",
    "Best way to prepare for exams",
    "Why do I get sleepy when studying?",
    "How to write a persuasive essay?",
    "Best websites for science experiments",
    "How to improve my handwriting?",
    "Best apps for learning piano",
    "Why is chemistry so confusing?",
    "How to make a study schedule?",
    "Best way to learn history dates",
    "How to write a lab report?",
    "Best websites for grammar check",
    "Why do I struggle with public speaking?",
    "How to take online classes effectively?",
    "Best apps for learning guitar",
    "How to summarize long articles?",
    "Best way to learn multiplication tables",
    "Why is my writing so repetitive?",
    "How to create a mind map?",
    "Best websites for learning programming",
    "How to stay motivated while learning?",
    "Best apps for learning chess",

    # Automotive (50)
    "How to jump start a car?",
    "Best oil for high mileage engines",
    "Why is my check engine light on?",
    "How to change a flat tire?",
    "Best car wax for black paint",
    "How to clean car headlights?",
    "Why is my car making a knocking sound?",
    "Best way to remove bumper stickers",
    "How to check transmission fluid?",
    "Best car seats for toddlers",
    "Why is my AC not cold in my car?",
    "How to remove scratches from car paint?",
    "Best dash cams for 2023",
    "How to fix a stuck car door?",
    "Why is my car battery dying?",
    "Best way to clean leather car seats",
    "How to program a car key fob?",
    "Best tire pressure for highway driving",
    "Why is my steering wheel shaking?",
    "How to remove tree sap from car?",
    "Best car phone mounts",
    "How to fix a car window that won't roll up?",
    "Why is my car overheating?",
    "Best way to remove snow from car",
    "How to clean car engine bay?",
    "Best floor mats for SUVs",
    "Why is my car pulling to one side?",
    "How to fix a car radio?",
    "Best way to protect car paint",
    "How to check brake fluid?",
    "Best car vacuums for pet hair",
    "Why is my gas mileage so poor?",
    "How to remove rust from car body?",
    "Best way to organize car trunk",
    "How to fix a stuck sunroof?",
    "Best car air fresheners",
    "Why is my car making a squealing noise?",
    "How to clean car dashboard?",
    "Best way to remove ice from windshield",
    "How to fix a car horn?",
    "Best jump starters for dead batteries",
    "Why is my car shaking when idle?",
    "How to remove oxidation from car paint?",
    "Best car covers for outdoor parking",
    "How to fix a stuck gas cap?",
    "Best way to clean car wheels",
    "Why is my car stereo not working?",
    "How to remove pet hair from car seats?",
    "Best portable air compressors",
    "Why is my car leaking fluid?",
    "How to fix a stuck car trunk?",

    # Shopping & Consumer (50)
    "How to return items on Amazon?",
    "Best time to buy a new TV",
    "Why was my credit card declined?",
    "How to find coupon codes?",
    "Best budget smartphones under $300",
    "How to cancel an online order?",
    "Why is my package delayed?",
    "Best places to sell used clothes",
    "How to track my FedEx package?",
    "Best budget laptops for students",
    "Why did I get charged twice?",
    "How to get a refund from eBay?",
    "Best wireless routers for home",
    "How to dispute a credit card charge?",
    "Why is my order status not updating?",
    "Best places to buy cheap flights",
    "How to contact Walmart customer service?",
    "Best noise-cancelling headphones under $100",
    "Why is my gift card not working?",
    "How to find the best deals online?",
    "Best budget tablets for kids",
    "How to return something without receipt?",
    "Why is my online payment not going through?",
    "Best places to buy cheap furniture",
    "How to cancel a subscription?",
    "Best budget cameras for beginners",
    "Why did my order get cancelled?",
    "How to get free shipping?",
    "Best places to buy refurbished electronics",
    "How to check my gift card balance?",
    "Best budget gaming laptops",
    "Why is my coupon code not working?",
    "How to track my USPS package?",
    "Best places to buy cheap textbooks",
    "How to get a price adjustment?",
    "Best budget smartwatches",
    "Why is my delivery date changing?",
    "How to return something to Target?",
    "Best places to buy cheap appliances",
    "How to contact Amazon seller?",
    "Best budget wireless earbuds",
    "Why is my refund taking so long?",
    "How to find the best Black Friday deals?",
    "Best places to buy cheap shoes",
    "How to get a replacement for damaged item?",
    "Best budget fitness trackers",
    "Why is my order still processing?",
    "How to cancel an eBay bid?",
    "Best places to buy cheap jewelry",
    "How to get a refund for lost package?",
    "Best budget printers for home use"
]

# Create validity labels (1 for banking, 0 for non-banking)
validity_x = x + non_banking_queries
validity_y = [1] * len(x) + [0] * len(non_banking_queries)

# Enhanced text preprocessing
def preprocess_text(text):
    text = str(text).lower()
    text = re.sub(r'[^\w\s]', '', text)  # Remove punctuation
    text = re.sub(r'\d+', '', text)      # Remove numbers
    text = re.sub(r'\s+', ' ', text).strip()  # Normalize whitespace
    return text

# Prepare data
X = np.array([preprocess_text(q) for q in x])
validity_X = np.array([preprocess_text(q) for q in validity_x])
validity_y = np.array(validity_y)
y = np.array(y)
priority = np.array(priority)

# Split data for validity classifier
X_validity_train, X_validity_test, y_validity_train, y_validity_test = train_test_split(
    validity_X, validity_y, 
    test_size=0.2, 
    random_state=42,
    stratify=validity_y
)

# Split data for category and priority models
X_train, X_test, y_train, y_test, pri_train, pri_test = train_test_split(
    X, y, priority, 
    test_size=0.2, 
    random_state=42,
    stratify=y
)

# Feature extraction
vectorizer = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1, 3),
    min_df=2,
    max_df=0.7,
    sublinear_tf=True,
    analyzer='word',
    stop_words='english'
)

# Validity Model - LinearSVC for binary classification
validity_vectorizer = TfidfVectorizer(
    max_features=8000,
    ngram_range=(1, 2),
    min_df=3,
    max_df=0.8,
    sublinear_tf=True,
    analyzer='word',
    stop_words='english'
)

X_validity_train_tfidf = validity_vectorizer.fit_transform(X_validity_train)
X_validity_test_tfidf = validity_vectorizer.transform(X_validity_test)

validity_model = LinearSVC(
    C=0.5,
    class_weight='balanced',
    random_state=42,
    max_iter=5000
)
validity_model.fit(X_validity_train_tfidf, y_validity_train)

# Category Model - SVC with class weights
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

category_model = CalibratedClassifierCV(
    SVC(
        kernel='rbf',
        C=1.5,
        class_weight='balanced',
        probability=True,
        random_state=42
    ),
    cv=5
)
category_model.fit(X_train_tfidf, y_train)

# Priority Model - Gradient Boosting with class weights
priority_model = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=10,
    random_state=42
)
priority_model.fit(X_train_tfidf, pri_train)

# Evaluation functions

def evaluate_model(model, X_test, y_test, model_type, target_names=None):
    y_pred = model.predict(X_test)
    print(classification_report(y_test, y_pred, target_names=target_names, zero_division=0))
    
    # Cross-validation only for models that support it
    from sklearn.model_selection import cross_val_score
    if model_type == 'category':
        # For CalibratedClassifierCV, we'll use cross_val_score directly on the calibrated model
        scores = cross_val_score(
            model, 
            X_train_tfidf, 
            y_train, 
            cv=5, 
            scoring='accuracy'
        )
    elif model_type == 'validity':
        # For LinearSVC
        scores = cross_val_score(
            model,
            X_validity_train_tfidf,
            y_validity_train,
            cv=5,
            scoring='accuracy'
        )
    elif model_type == 'priority':
        # For GradientBoosting, we'll skip cross-validation
        print("Cross-validation not shown for GradientBoosting priority model")
        return
    
    print(f"Cross-validated accuracy: {np.mean(scores):.2f} ± {np.std(scores):.2f}")

print("Validity Model Performance:")
evaluate_model(
    validity_model, 
    X_validity_test_tfidf, 
    y_validity_test, 
    model_type='validity',
    target_names=['non-banking', 'banking']
)

print("\nCategory Model Performance:")
evaluate_model(
    category_model, 
    X_test_tfidf, 
    y_test, 
    model_type='category'
)

print("\nPriority Model Performance:")
evaluate_model(
    priority_model, 
    X_test_tfidf, 
    pri_test, 
    model_type='priority'
)
# Test with sample queries
test_queries = [
    "If a flower bloomed in a dark room",
    "How to open a savings account?",
    "What's the interest rate for home loans?",
    "I lost my debit card",
    "How to check account balance via SMS?",
    "Can I get a duplicate passbook?",
    "I want to close my account",
    "Need help linking Aadhaar to my account",
    "How to apply for a credit card?",
    "Transaction failed but amount deducted",
    "Change my net banking password",
    "Activate mobile banking",
    "Block my credit card immediately",
    "Is my loan approved?",
    "How to stop a cheque payment?",
    "What's the current FD interest rate?",
    "I forgot my UPI PIN",
    "How to increase credit card limit?",
    "Request for account statement",
    "How to change registered mobile number?",
    "Lost my phone with banking app",
    "Need EMI schedule for home loan",
    "Status of personal loan application",
    "Can I pay EMI in advance?",
    "Download TDS certificate",
    "What documents are needed for KYC?",
    "How to reset netbanking credentials?",
    "Failed to receive OTP",
    "Delay in cheque clearance",
    "ATM swallowed my card",
    "Transfer money to another bank",
    "Facing issues with netbanking login",
    "Update PAN in my account",
    "New cheque book request",
    "Cash deposit limit per day?",
    "What's the cut-off time for NEFT?",
    "Interest not credited to savings account",
    "Can I break my FD early?",
    "Enable international usage on card",
    "Transaction marked suspicious",
    "Enable two-factor authentication",
    "Redeem my credit card points",
    "Need clarification on service charges",
    "Change name on account after marriage",
    "Reopen closed account",
    "What is SWIFT code for international transfer?",
    "Schedule a recurring deposit",
    "UPI payment not reflecting",
    "Stop auto-debit for insurance",
    "Download interest certificate",
    "Change nominee for fixed deposit",
    "My mobile banking app keeps crashing",
    "Customer ID not working",
    "Need home loan foreclosure statement",
    "Reschedule missed EMI",
    "Unblock my debit card",
    "Balance showing incorrectly",
    "Account frozen – what to do?",
    "Dispute a credit card transaction",
    "Loan tenure extension request",
    "Can I convert purchases to EMI?",
    "Cashback not received",
    "Loan interest calculation clarification",
    "Incorrect Aadhaar linked",
    "Failed e-mandate setup",
    "Form 16A request",
    "Need old account statement",
    "What is the loan processing fee?",
    "Add joint holder to account",
    "What's the penalty for FD pre-closure?",
    "Request for NOC on closed loan",
    "Cheque returned reason query",
    "Modify ECS mandate",
    "Transaction stuck in processing",
    "How to disable contactless card?",
    "Online banking UI feedback",
    "Enable standing instruction",
    "Loan part-payment procedure",
    "Unable to view credit card bill",
    "Blocked from mobile app login",
    "Reset MPIN for mobile banking",
    "Is there a fee for balance enquiry?",
    "Mortgage interest certificate request",
    "Unable to redeem reward points",
    "Query about failed fund transfer",
    "Closed RD not reflecting",
    "Digital locker access issue",
    "Debit card daily limit",
    "Online account opening not working",
    "Missed call balance check not working",
    "E-statement not received",
    "Card delivery delayed",
    "Request to convert current account to savings",
    "Need account number reminder",
    "Lost cheque book request",
    "I'm hungry and want food",
    "What's the weather today?",
    "How to bake a chocolate cake?",
    "Tell me a joke",
    "Where is my parcel?",
    "What is the capital of Spain?",
    "Play my favorite music",
    "Open YouTube",
    "Who won the cricket match?",
    "Set an alarm for 6 AM"
]

# Enhanced non-banking queries to better distinguish edge cases
enhanced_non_banking = non_banking_queries + [
    # Add more ambiguous examples
    "How to reset my router password",
    "What's the code for my alarm system",
    "Failed to receive my package",
    "Delay in my flight clearance",
    "Facing issues with my email login",
    "New book request at library",
    "What's the cut-off time for dinner?",
    "What is code for international shipping?",
    "Stop auto-renewal for my magazine",
    "Cashback not received on my shopping",
    "Failed setup of my home security",
    "What's the penalty for late return?",
    "Book returned reason query",
    "Modify my gym membership",
    "Unable to redeem my coupons",
    "Closed account not reflecting",
    "Digital photo access issue",
    "E-ticket not received",
    "Lost book request"
]

# Update validity data
validity_x = x + enhanced_non_banking
validity_y = [1] * len(x) + [0] * len(enhanced_non_banking)

# Update validity model with better parameters
validity_model = LinearSVC(
    C=1.0,  # Reduced regularization
    class_weight={0: 1, 1: 1.2},  # Slightly favor banking queries
    random_state=42,
    max_iter=10000
)
validity_model.fit(X_validity_train_tfidf, y_validity_train)

# Add banking keywords as fallback validation
banking_keywords = {
    # Account terms
    'account', 'savings', 'current', 'deposit', 'withdrawal', 'balance', 'statement',
    'passbook', 'cheque', 'chequebook', 'overdraft', 'dormant', 'kyc', 'nominee',
    'joint account', 'minor account', 'nri account', 'fcnr', 'nre', 'nro',
    
    # Loan terms
    'loan', 'mortgage', 'emi', 'foreclosure', 'prepayment', 'interest rate', 'tenure',
    'principal', 'collateral', 'personal loan', 'home loan', 'car loan', 'education loan',
    'business loan', 'gold loan', 'loan against property', 'top-up loan', 'balance transfer',
    'part payment', 'moratorium', 'loan statement', 'noc', 'loan closure',
    
    # Card terms
    'card', 'debit', 'credit', 'atm', 'pin', 'cvv', 'expiry', 'contactless', 'reward points',
    'cashback', 'billing cycle', 'credit limit', 'add-on card', 'virtual card', 'cardless withdrawal',
    'international usage', 'card block', 'hotlist', 'card replacement', 'emi conversion',
    
    # Digital banking
    'netbanking', 'mobile banking', 'internet banking', 'upi', 'imps', 'neft', 'rtgs', 'swift',
    'beneficiary', 'mmid', 'otp', 'mpin', 'upi pin', 'qr code', 'biometric login', 'standing instruction',
    'auto-debit', 'e-mandate', 'recurring payment', 'fastag', 'aeps', 'dbt', 'digilocker',
    
    # Investment terms
    'fd', 'rd', 'recurring deposit', 'fixed deposit', 'demat', 'mutual fund', 'sip', 'swp', 'stp',
    'nps', 'ppf', 'scss', 'sukanya samriddhi', 'elss', 'sovereign gold bond', 'capital gain',
    'dividend', 'portfolio', 'redemption', 'systematic withdrawal', 'folio', 'kvb', 'nfo',
    
    # Transaction terms
    'transaction', 'transfer', 'payment', 'failed transaction', 'dispute', 'chargeback', 'reversal',
    'refund', 'cash deposit', 'cheque deposit', 'clearing', 'bounce', 'stop payment', 'transaction limit',
    'daily limit', 'pos', 'ecom', 'contactless', 'international transaction', 'currency conversion',
    
    # General banking terms
    'branch', 'ifsc', 'micr', 'swift code', 'customer id', 'service charge', 'penalty', 'minimum balance',
    'quarterly average balance', 'locker', 'nomination', 'signature', 'aadhaar', 'pan', 'fatca', 'crs',
    'form 15g', 'form 15h', 'form 16a', 'tds', 'interest certificate', 'tax saver', 'itr', 'gst',
    
    # Common abbreviations
    'atm', 'pos', 'cvv', 'otp', 'pin', 'kyc', 'emi', 'nps', 'ppf', 'rd', 'fd', 'nre', 'nro', 'fcnr',
    'neft', 'rtgs', 'imps', 'upi', 'aeps', 'dbt', 'nach', 'ecs', 'swift', 'ifsc', 'micr', 'crs',
    'elss', 'sip', 'swp', 'stp', 'nfo', 'kvb', 'itr', 'gst', 'tds', 'pan', 'aadhaar'
}

banking_patterns = [
    r'how (to|do i) (open|close|update|change|check) (my|an) (account|loan|card|fd|rd)',
    r'what (is|are) (the|your) (interest rate|charges|fees|limit|balance|procedure)',
    r'i (need|want|lost|forgot|require) (to|my|a) (account|loan|card|statement|pin|password)',
    r'how (much|many|long) (does|is|are) (the|it|my) (account|loan|card|fd|rd)',
    r'can i (get|have|apply|use|change) (a|my|the) (account|loan|card|fd|rd)',
    r'where (is|can) (i|my) (account|loan|card|statement|details)',
    r'why (is|did|has) (my|the) (account|loan|card|transaction)',
    r'when (will|can) (i|my) (account|loan|card|transaction)',
    r'help (with|for) (my|the) (account|loan|card|transaction)',
    r'problem (with|in) (my|the) (account|loan|card|transaction)',
    r'issue (with|in) (my|the) (account|loan|card|transaction)',
    r'failed (to|in) (my|the) (account|loan|card|transaction)',
    r'not (working|received|credited|updated) (my|the) (account|loan|card|transaction)',
    r'how (to|do i) (link|update|change|verify) (my|aadhaar|pan)',
    r'what (documents|papers|details) (are|do) (needed|required)',
    r'how (to|do i) (apply|register|activate|block) (for|my)',
    r'request (for|to) (my|a|the) (account|loan|card|statement)',
    r'need (to|help|assistance) (with|for) (my|the) (account|loan|card)',
    r'status (of|for) (my|the) (account|loan|card|application)',
    r'information (about|on) (my|the) (account|loan|card|fd)'
]


def is_banking_query(text, strict=False):
    """
    Enhanced banking query detection with multiple validation layers
    """
    processed = preprocess_text(text)
    
    # Basic checks
    if len(processed.split()) < 3:  # Very short queries are unlikely to be banking
        return False
    
    # Check with validity classifier first
    validity_vec = validity_vectorizer.transform([processed])
    is_banking = validity_model.predict(validity_vec)[0]
    proba = validity_model._predict_proba_lr(validity_vec)[0][1]  # Get probability
    
    # For strict mode, require higher confidence
    if strict and proba < 0.7:
        return False
    
    # Secondary checks
    if not is_banking:
        # Check for banking keywords if classifier is unsure
        if any(keyword in processed for keyword in banking_keywords):
            return True
        
        # Check for common banking query patterns
        if any(re.search(pattern, processed) for pattern in banking_patterns):
            return True
    
    return is_banking


# Modified query processing
for query in test_queries:
    processed = preprocess_text(query)
    
    # First check with validity classifier
    validity_vec = validity_vectorizer.transform([processed])
    is_banking = validity_model.predict(validity_vec)[0]
    
    # Secondary check for borderline cases
    if not is_banking and is_banking_query(processed):
        is_banking = True  # Override if banking keywords found
    
    print(f"\nQuery: {query}")
    if not is_banking:
        print("Result: REJECTED (non-banking query)")
    else:
        vec = vectorizer.transform([processed])
        cat_pred = category_model.predict(vec)[0]
        pri_pred = priority_model.predict(vec)[0]
        print(f"Result: Category={cat_pred}, Priority={pri_pred}")

# Expose components needed by FastAPI
__all__ = [
    'preprocess_text',
    'validity_vectorizer',
    'validity_model',
    'vectorizer',
    'category_model',
    'priority_model',
    'is_banking_query'
]